---
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1
  aws-ecr: circleci/aws-ecr@9.0

prelude: &prelude
  docker:
  - image: golang:1.19-alpine
  working_directory: ~/babylon

use_docker: &use_docker setup_remote_docker

ecr_login: &ecr_login
  - aws-cli/setup:
      role_arn: arn:aws:iam::830214760947:role/sdr-cci-terraform-provider-azuredevops
  - aws-ecr/ecr_login:
      account_id: '830214760947'
      region: eu-west-2

install_base: &install_base
  run: apk add git bash curl gcc build-base g++ jq libc-dev openssh-client

install_docker: &install_docker
  run: apk add docker

only_master: &only_master
  filters:
    branches:
      only:
      - master

not_master: &not_master
  filters:
    branches:
      ignore:
      - master

only_tagged: &only_tagged
  filters:
    branches:
      ignore:
      - /^.*$/
    tags:
      only:
      - /^v.*-babylon.*$/

workflows:
  pr-flow:
    jobs:
    - test:
        <<: *not_master
    - build:
        context: babylon
        <<: *not_master

  master-flow:
    jobs:
    - build:
        context: babylon
        <<: *only_master

  semver-flow:
    jobs:
    - tag-semver:
        context: babylon
        <<: *only_tagged

jobs:
  test:
    <<: *prelude
    steps:
    - *install_base
    - checkout
    - run: babylon/build test
  build:
    <<: *prelude
    steps:
    - *install_base
    - *install_docker
    - checkout
    - *use_docker
    - *ecr_login
    - run: babylon/build build
    - run: babylon/build install
  tag-semver:
    <<: *prelude
    steps:
    - *install_base
    - *install_docker
    - checkout
    - *use_docker
    - *ecr_login
    - run: babylon/build tag-semver
