package githubappclient

import "net/http"

type GitHubAppPayload struct {
	ContributionIds     []string            `json:"contributionIds"`
	DataProviderContext DataProviderContext `json:"dataProviderContext"`
}
type RouteValues struct {
	Project string `json:"project"`
}
type SourcePage struct {
	RouteValues RouteValues `json:"routeValues"`
}

type AutoGenerated struct {
	ContributionIds     []string            `json:"contributionIds"`
	DataProviderContext DataProviderContext `json:"dataProviderContext"`
}

type Properties struct {
	SourceProvider string     `json:"sourceProvider,omitempty"`
	RepositoryID   string     `json:"repositoryId,omitempty"`
	RepositoryName string     `json:"repositoryName,omitempty"`
	ConnectionID   string     `json:"connectionId,omitempty"`
	StrongBoxKey   string     `json:"strongBoxKey,omitempty"`
	SourcePage     SourcePage `json:"sourcePage,omitempty"`

	ServiceEndpointID string `json:"serviceEndpointId,omitempty"`
	ProjectID         string `json:"projectId,omitempty"`
}
type DataProviderContext struct {
	Properties Properties `json:"properties"`
}

type AddGitAppResp struct {
	DataProviders struct {
		MsVssBuildWebAppServiceconnectionsRecommendationDataProvider struct {
			CommonConnectionID string `json:"commonConnectionId"`
		} `json:"ms.vss-build-web.app-serviceconnections-recommendation-data-provider"`
	} `json:"dataProviders"`
}

type GithubApp struct {
	baseUrl       string
	client        *http.Client
	authorization string
}

type GetGithubAppResponse struct {
	DataProviderExceptions DataProviderExceptions `json:"dataProviderExceptions"`
	DataProviders          DataProviders          `json:"dataProviders"`
}
type MsVssServiceEndpointsWebServiceEndpointsDetailsDataProvider struct {
	ExceptionType   string          `json:"exceptionType"`
	Message         string          `json:"message"`
	ServiceEndpoint ServiceEndpoint `json:"serviceEndpoint"`
}
type DataProviderExceptions struct {
	MsVssServiceEndpointsWebServiceEndpointsDetailsDataProvider MsVssServiceEndpointsWebServiceEndpointsDetailsDataProvider `json:"ms.vss-serviceEndpoints-web.service-endpoints-details-data-provider"`
}
type Authorization struct {
	Scheme string `json:"scheme"`
}
type ProjectReference struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
type ServiceEndpointProjectReferences struct {
	ProjectReference ProjectReference `json:"projectReference"`
	Name             string           `json:"name"`
}
type ServiceEndpoint struct {
	ID                               string                             `json:"id"`
	Name                             string                             `json:"name"`
	Authorization                    Authorization                      `json:"authorization"`
	ServiceEndpointProjectReferences []ServiceEndpointProjectReferences `json:"serviceEndpointProjectReferences"`
}

type DataProviders struct {
	MsVssServiceEndpointsWebServiceEndpointsDetailsDataProvider MsVssServiceEndpointsWebServiceEndpointsDetailsDataProvider `json:"ms.vss-serviceEndpoints-web.service-endpoints-details-data-provider"`
}
