ARG SHA_VERSION

FROM quay.io/babylonhealth/azure-terraform:${SHA_VERSION}

ARG SEMVER_VERSION

RUN \
    set -eux \
    && cd /root/.terraform.d/plugins/babylonhealth.com/babylonhealth/azuredevops/ \
    && ls -la \
    && mv "$(ls)" "${SEMVER_VERSION}"
