#!/usr/bin/env bash

set -euxo pipefail

git remote remove microsoft-origin || echo "ignoring missing remote"

git remote add microsoft-origin https://github.com/microsoft/terraform-provider-azuredevops.git

git fetch microsoft-origin

MS_TAG=$(git describe --abbrev=0 --tags microsoft-origin/master)

git checkout master

git pull origin master

git checkout -B sync-${MS_TAG}

git merge --allow-unrelated-histories tags/${MS_TAG}